Update ping.yml

diff --git a/.github/workflows/ping.yml b/.github/workflows/ping.yml
--- a/.github/workflows/ping.yml
+++ b/.github/workflows/ping.yml
@@ -10,4 +10,4 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Ping Render App
-        run: curl -fsS https://task-tapper.onrender.com/api/auth || echo "Ping failed"
+        run: curl -fsS https://task-tapper.onrender.com/api/ping || echo "Ping failed"
